title: Categories
modelClass: Mavitm\Estate\Models\Category
list: $/mavitm/estate/models/category/columns.yaml
recordUrl: 'mavitm/estate/categories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
